<a href="https://colab.research.google.com/github/jstrend/lecture/blob/main/numpy_example_choki0715.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np # numpy는 클래스 numpy.array는 넘파이 클래스 하부 함수

# ndarray basic
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 dimension array indexing할때는 ,사용 
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [ ]:
# ndarray 설정

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array with 7
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix with eye
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

f = np.empty((3,3)) # empty는 쓰레기 값을 보여줌, 보통 초기화해서 사용해야 함
print(f)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.81562443 0.5325044 ]
 [0.83952282 0.97618825]]
[[4.68937941e-310 4.68937940e-310 4.68937940e-310]
 [4.68937940e-310 4.68937940e-310 4.68937940e-310]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [ ]:
# indexing 인덱싱

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]" a는 3x2 어레이, (행위치,열위치)로 쌍을 만들어 페어로 사용

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [9]:
# Broadcasting 주요한 기능 Matlab과 비슷한 numpy

import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]) # 4x3 matrix
w = np.array([[1,0,1], [1,0,1], [1,0,1], [1,0,1]])
v = np.array([1, 0, 1]) # 1x3 matrix
y1 = x + v  # Add v to each row of x using broadcasting 크기가 달라 더하기 어려우나 broadcasting하게 되서 모든 행에 모두 더해줌
y2 = x + w
print("y1 = ", y1, "\n y2 =" , y2)  # y1 = Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"
          # y2 = x + w

y1 =  [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]] 
 y2 = [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [12]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]) # 4x3 matrix
w = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1, 0]) # 1x4 matrix
v = v.reshape(4,1) 
y = x + v  # Add v to each row of x using broadcasting 크기가 달라 더하기 어려우나 broadcasting하게 되서 모든 열에 모두 더해줌
print("y = ", y)  # y = Prints "[[ 2  3  4]
          #          [ 4  5  6]
          #          [ 8  9 10]
          #          [10 11 12]]"
          # y2 = x + w

y =  [[ 2  3  4]
 [ 4  5  6]
 [ 8  9 10]
 [10 11 12]]


In [ ]:
# Math
mat1 = np.ones((3,3))
print(mat1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
cnt = 1
mat2 = np.zeros((3,3))
for i in range(3):
  for j in range(3):
    mat2[i,j] = mat1[i,j]*cnt
    cnt = cnt + 1
print(mat2)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
mat3 = (mat1 + mat2) * mat2 - mat1/mat2
print(mat3)

mat3_1 = np.subtract( np.multiply( np.add(mat1, mat2), mat2), np.divide(mat1,mat2) ) # np.multiply는 사이즈가 같으면 요소간 곱하기
print(mat3_1)

[[ 1.          5.5        11.66666667]
 [19.75       29.8        41.83333333]
 [55.85714286 71.875      89.88888889]]
[[ 1.          5.5        11.66666667]
 [19.75       29.8        41.83333333]
 [55.85714286 71.875      89.88888889]]


In [ ]:
mat4 = np.dot(mat2, mat3) # 가능하면 matmul을 사용 dot는 다른 라이브러리 사용x
print(mat4)

[[ 208.07142857  280.725       365.        ]
 [ 437.89285714  602.25        795.16666667]
 [ 667.71428571  923.775      1225.33333333]]


In [ ]:
mat5 = np.matmul(mat2, mat3) # matmul은 행렬 곱
print(mat5)

[[ 208.07142857  280.725       365.        ]
 [ 437.89285714  602.25        795.16666667]
 [ 667.71428571  923.775      1225.33333333]]


In [ ]:
vec = np.array([1,2,3])
print(vec)

[1 2 3]


In [ ]:
mat6 = np.dot(mat2, vec)
print(mat6)

[14. 32. 50.]


In [ ]:
mat7 = np.matmul(mat2, vec)
print(mat7)

[14. 32. 50.]
